package com.ahancer.rr.models;
// Generated Aug 18, 2016 5:27:59 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CampaignResourceId generated by hbm2java
 */
@Embeddable
public class CampaignResourceId implements java.io.Serializable {

	private static final long serialVersionUID = 6043666580459930750L;
	
	@Column(name = "campaignId", nullable = false)
	private long campaignId;
	
	@Column(name = "resourceId", nullable = false)
	private long resourceId;

	public CampaignResourceId() {
	}

	public CampaignResourceId(long campaignId, long resourceId) {
		this.campaignId = campaignId;
		this.resourceId = resourceId;
	}
	
	public long getCampaignId() {
		return this.campaignId;
	}

	public void setCampaignId(long campaignId) {
		this.campaignId = campaignId;
	}

	
	public long getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(long resourceId) {
		this.resourceId = resourceId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CampaignResourceId))
			return false;
		CampaignResourceId castOther = (CampaignResourceId) other;

		return (this.getCampaignId() == castOther.getCampaignId())
				&& (this.getResourceId() == castOther.getResourceId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCampaignId();
		result = 37 * result + (int) this.getResourceId();
		return result;
	}

}
